DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS courses;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);


CREATE TABLE courses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL UNIQUE,
  desc TEXT NOT NULL,
  needed INTEGER NOT NULL DEFAULT 0
);
